package tw.jruletest.parse.ruletree;

import tw.jruletest.exceptions.InvalidRuleStructureException;

/**
 * Interface for the expected implementation of nodes to be added to a tree in order to validate rules and generate the required code.
 *
 * @author Toby Wride
 * */

public interface TreeNode {

    /**
     * Generate code based on child nodes' code generation and any extra syntax required for the code to compile.
     *
     * @return the code generated by the node.
     * */

    String generateCode();

    /**
     * Validates the structure of the rule based on expected structures and validity of the rule determined by the required child nodes
     *
     * @param ruleContent rule segment to be validated
     *
     * @return the index required to extract the valid segment from the rule
     *
     * @throws InvalidRuleStructureException thrown if the rule is not found to be valid.
     * */

    int validateRule(String ruleContent) throws InvalidRuleStructureException;
}
